const LOGIN_ERROR = "LOGIN_USER";
const LOGIN_LOADING = "LOGIN_USER_LOADING";
const LOGIN_SUCCESS = "LOGIN_USER_SUCCESS";
const REGISTER_ERROR = "REGISTER_USER";
const REGISTER_LOADING = "REGISTER_USER_LOADING";
const REGISTER_SUCCESS = "REGISTER_USER_SUCCESS";
const LOGOUT = "LOGOUT_USER";
const LOGOUT_LOADING = "LOGOUT_USER_LOADING";
const LOGOUT_SUCCESS = "LOGOUT_USER_SUCCESS";

export {LOGIN_ERROR,LOGIN_LOADING,LOGIN_SUCCESS,REGISTER_ERROR,REGISTER_LOADING,REGISTER_SUCCESS,LOGOUT,LOGOUT_LOADING,LOGOUT_SUCCESS};