const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
const DELETE_PRODUCT_LOADING = "DELETE_PRODUCT_LOADING";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

const CHECKOUT_PRODUCT_ERROR = "CHECKOUT_PRODUCT_ERROR";
const CHECKOUT_PRODUCT_LOADING = "CHECKOUT_PRODUCT_LOADING";
const CHECKOUT_PRODUCT_SUCCESS = "CHECKOUT_PRODUCT_SUCCESS";

export {ADD_PRODUCT_ERROR,ADD_PRODUCT_LOADING,ADD_PRODUCT_SUCCESS,DELETE_PRODUCT_ERROR,DELETE_PRODUCT_LOADING,DELETE_PRODUCT_SUCCESS,GET_PRODUCT_ERROR,GET_PRODUCT_LOADING,GET_PRODUCT_SUCCESS,CHECKOUT_PRODUCT_ERROR,CHECKOUT_PRODUCT_LOADING,CHECKOUT_PRODUCT_SUCCESS}